// Package domain holds the community module's aggregates: the tenancy
// conversation and the gate pass.
package domain

import (
	"errors"
	"strings"
	"time"
)

// Message is one line of a tenancy's conversation.
type Message struct {
	ID       string
	TenantID string
	LeaseID  string
	// PropertyID and UnitID ride on the row for the delegation quad (ADR-0009).
	PropertyID string
	UnitID     string

	Sender        string // resident | manager | system
	SenderPartyID string
	Body          string
	CreatedAt     time.Time
}

// ErrMessage is a message that cannot be sent as written.
var ErrMessage = errors.New("community: invalid message")

// ValidateSend refuses what the schema would refuse, with a usable reason.
func (m Message) ValidateSend() error {
	if strings.TrimSpace(m.Body) == "" {
		return errors.Join(ErrMessage, errors.New("an empty message says nothing"))
	}
	if len(m.Body) > 4000 {
		return errors.Join(ErrMessage, errors.New("that is longer than a message"))
	}
	if m.LeaseID == "" || m.PropertyID == "" || m.UnitID == "" {
		return errors.Join(ErrMessage, errors.New("the tenancy is not resolved"))
	}
	return nil
}

// PassKind is what kind of visit a gate pass covers.
type PassKind string

var passKinds = map[PassKind]bool{"guest": true, "delivery": true, "cab": true, "help": true}

// Known reports whether this is a kind the schema will accept.
func (k PassKind) Known() bool { return passKinds[k] }

// Pass is one expected visitor.
type Pass struct {
	ID        string
	TenantID  string
	LeaseID   string
	PropertyID string
	UnitID     string
	CreatedBy string

	Name      string
	Kind      PassKind
	// Code is what the visitor says at the gate — four digits, generated by
	// the store, never chosen by the caller.
	Code      string
	ValidFrom time.Time
	ValidTo   time.Time

	State     string // expected | cancelled | arrived | inside | left | denied
	CreatedAt time.Time
	UpdatedAt time.Time
}

// ErrPass is a pass that cannot be created as described.
var ErrPass = errors.New("community: invalid gate pass")

// ValidateCreate refuses what the schema would refuse.
func (p Pass) ValidateCreate() error {
	if strings.TrimSpace(p.Name) == "" {
		return errors.Join(ErrPass, errors.New("the gate needs a name"))
	}
	if !p.Kind.Known() {
		return errors.Join(ErrPass, errors.New("unknown kind of visit"))
	}
	if p.LeaseID == "" || p.PropertyID == "" || p.UnitID == "" || p.CreatedBy == "" {
		return errors.Join(ErrPass, errors.New("the tenancy is not resolved"))
	}
	return nil
}
